# task
task_type: MrcTaggingTask
task_name: GPwRoPE_W2_MSRA
comment: 'bert mrc w/ w2ner for NER'

# data preprocessing
max_seq_len: 512
negative_sample_prob: 1.0
debug_mode: false
mode: w2

# filepaths
# plm_dir: /data/tzhu/PLM/hfl--rbt3
# base_model_path: outputs/rbt3_w2mrc_GPwRoPE_cmrc2018All/ckpt/MrcGlobalPointerModel.best.pth
# plm_dir: /data/tzhu/PLM/bert-base-chinese
plm_dir: /data/tzhu/PLM/hfl--chinese-roberta-wwm-ext
# plm_dir: /data/tzhu/PLM/hfl--chinese-roberta-wwm-ext-large
data_dir: resources/NER/msra/formatted
output_dir: outputs
task_dir: ${output_dir}/${task_name}
train_filepath: ${data_dir}/train.jsonl
dev_filepath: ${data_dir}/test.jsonl
test_filepath: ${data_dir}/test.jsonl
ent_type2query_filepath: resources/query.json
dump_cache_dir: ${task_dir}/cache
regenerate_cache: true

# training
random_seed: 1227
eval_on_data: [dev]
select_best_on_data: dev
select_best_by_key: metric
best_metric_field: micro.f1
final_eval_on_test: true

warmup_proportion: 0.1
num_epochs: 20
epoch_patience: 5
train_batch_size: 16
eval_batch_size: 32
learning_rate: !!float 2e-5
other_learning_rate: !!float 2e-5

# model
dropout: 0.3
biaffine_size: 512
