cd resources/Mirror/v1.3
out_dir="merged_pretrained_data"
mkdir $out_dir

cat \
    ./cls/en/ag_news/instructed/train.jsonl \
    ./cls/en/ANLI/R1_processed/train.jsonl \
    ./cls/en/ANLI/R2_processed/train.jsonl \
    ./cls/en/ANLI/R3_processed/train.jsonl \
    ./cls/en/ARC/new/train.jsonl \
    ./cls/en/CoLA/formated/train.jsonl \
    ./cls/en/CosmosQA/new/train.jsonl \
    ./cls/en/cos_e/new/train.jsonl \
    ./cls/en/dbpedia/new/train.jsonl \
    ./cls/en/DREAM/new/train.jsonl \
    ./cls/en/hellaswag/processed/hellaswag_train.jsonl \
    ./cls/en/IMDB/formated/IMDB_train.jsonl \
    ./cls/en/MCTest/new/train_160.jsonl \
    ./cls/en/MCTest/new/train_500.jsonl \
    ./cls/en/MedQA/new/train.jsonl \
    ./cls/en/MNLI/formated/MNLI_train.jsonl \
    ./cls/en/MRPC/formated/train.jsonl \
    ./cls/en/MultiRC/instructed/train.jsonl \
    ./cls/en/OpenBookQA/new/train.jsonl \
    ./cls/en/QASC/new/train.jsonl \
    ./cls/en/QNLI/processed/QNLI_train.jsonl \
    ./cls/en/QQP/new/train.jsonl \
    ./cls/en/RACE/instructed/train.jsonl \
    ./cls/en/RACE-C/new/train.jsonl \
    ./cls/en/ReClor/new/train.jsonl \
    ./cls/en/RTE/formated/RTE_train.jsonl \
    ./cls/en/SciQ/instructed/train.jsonl \
    ./cls/en/SNLI/instructed/train.jsonl \
    ./cls/en/SST-2/instructed/SST-2_train.jsonl \
    ./cls/en/Winogrande/new/train.jsonl \
    ./cls/en/WNLI/processed/WNLI_train.jsonl \
    ./ent/en/ACE05-EN/instructed/train.jsonl \
    ./ent/en/ACE05-EN-plus/instructed/train.jsonl \
    ./ent/en/ACE_2004/instructed/train.jsonl \
    ./ent/en/AnatEM/instructed/train.jsonl \
    ./ent/en/bc2gm/instructed/train.jsonl \
    ./ent/en/bc4chemd/instructed/train.jsonl \
    ./ent/en/bc5cdr/instructed/train.jsonl \
    ./ent/en/Broad_Tweet_Corpus/instructed/train.jsonl \
    ./ent/en/CoNLL2003/instructed/train.jsonl \
    ./ent/en/CrossNER_AI/instructed/train.jsonl \
    ./ent/en/CrossNER_literature/instructed/train.jsonl \
    ./ent/en/CrossNER_music/instructed/train.jsonl \
    ./ent/en/CrossNER_politics/instructed/train.jsonl \
    ./ent/en/CrossNER_science/instructed/train.jsonl \
    ./ent/en/FabNER/instructed/train.jsonl \
    ./ent/en/FindVehicle/instructed/train.jsonl \
    ./ent/en/GENIA_NER/instructed/train.jsonl \
    ./ent/en/HarveyNER/instructed/train.jsonl \
    ./ent/en/MIT_MOVIE_Review/instructed/train.jsonl \
    ./ent/en/MIT_Restaurant_Review/instructed/train.jsonl \
    ./ent/en/MultiNERD/instructed/train.jsonl \
    ./ent/en/NCBIdiease/instructed/train.jsonl \
    ./ent/en/ontoNotes5/instructed/train.jsonl \
    ./ent/en/TweetNER7/instructed/train.jsonl \
    ./ent/en/WikiANN_en/instructed/train.jsonl \
    ./ent/en/WNUT-16/train.jsonl \
    ./event/en/ACE05-EN/instructed/train.jsonl \
    ./event/en/ACE05-EN-plus/fixed_instructed/train.jsonl \
    ./event/en/CASIE/instructed/train.jsonl \
    ./event/en/PHEE/instructed/train.jsonl \
    ./rel/en/14lap/instructed/train.jsonl \
    ./rel/en/14res/instructed/train.jsonl \
    ./rel/en/15res/instructed/train.jsonl \
    ./rel/en/16res/instructed/train.jsonl \
    ./rel/en/ACE05-EN/instructed/ACE2005_oneie_RE_labelmap_train.jsonl \
    ./rel/en/ACE05-EN-plus/instructed/ACE2005_plus_RE_labelmap_train.jsonl \
    ./rel/en/ADE_corpus/instructed/ADE_corpus_train.jsonl \
    ./rel/en/CoNLL2004/instructed/CoNLL2004_RE_labelmap_train.jsonl \
    ./rel/en/GIDS/instructed/GIDS_train.jsonl \
    ./rel/en/kbp37/instructed/kbp37_train.jsonl \
    ./rel/en/New-York-Times-RE/instructed/New_York_Times_train.jsonl \
    ./rel/en/NYT11HRL/instructed/NYT11HRL_train.jsonl \
    ./rel/en/NYT_multi/instructed/NYT_multi_train.jsonl \
    ./rel/en/sciERC/instructed/sciERC_train.jsonl \
    ./rel/en/T-REx/instructed/t-rex.udi.fix.jsonl \
    ./rel/en/Wiki-ZSL/instructed/Wiki_ZSL_0_train.jsonl \
    ./rel/en/Wiki-ZSL/instructed/Wiki_ZSL_1_train.jsonl \
    ./rel/en/Wiki-ZSL/instructed/Wiki_ZSL_2_train.jsonl \
    ./rel/en/Wiki-ZSL/instructed/Wiki_ZSL_3_train.jsonl \
    ./rel/en/Wiki-ZSL/instructed/Wiki_ZSL_4_train.jsonl \
    ./span/en/BiPaR/train.jsonl \
    ./span/en/ms_marco_v2.1/train.jsonl \
    ./span/en/newsqa/train.jsonl \
    ./span/en/squad_v2/train.jsonl \
    ./span/en/SubjQA/books/train.jsonl \
    ./span/en/SubjQA/electronics/train.jsonl \
    ./span/en/SubjQA/grocery/train.jsonl \
    ./span/en/SubjQA/movies/train.jsonl \
    ./span/en/SubjQA/restaurants/train.jsonl \
    ./span/en/SubjQA/tripadvisor/train.jsonl \
        > $out_dir/train.jsonl

cat \
    ./cls/en/ANLI/R1_processed/dev.jsonl \
    ./cls/en/ANLI/R2_processed/dev.jsonl \
    ./cls/en/ANLI/R3_processed/dev.jsonl \
    ./cls/en/ARC/new/dev.jsonl \
    ./cls/en/CosmosQA/new/dev.jsonl \
    ./cls/en/cos_e/new/dev.jsonl \
    ./cls/en/DREAM/new/dev.jsonl \
    ./cls/en/hellaswag/processed/hellaswag_dev.jsonl \
    ./cls/en/IMDB/formated/IMDB_dev.jsonl \
    ./cls/en/MCTest/new/dev_160.jsonl \
    ./cls/en/MCTest/new/dev_500.jsonl \
    ./cls/en/MedQA/new/dev.jsonl \
    ./cls/en/MNLI/formated/MNLI_dev.jsonl \
    ./cls/en/MRPC/formated/dev.jsonl \
    ./cls/en/MultiRC/instructed/dev.jsonl \
    ./cls/en/OpenBookQA/new/dev.jsonl \
    ./cls/en/QASC/new/dev.jsonl \
    ./cls/en/QNLI/processed/QNLI_dev.jsonl \
    ./cls/en/QQP/new/dev.jsonl \
    ./cls/en/RACE/instructed/dev.jsonl \
    ./cls/en/RACE-C/new/dev.jsonl \
    ./cls/en/ReClor/new/dev.jsonl \
    ./cls/en/RTE/formated/RTE_dev.jsonl \
    ./cls/en/SciQ/instructed/dev.jsonl \
    ./cls/en/SNLI/instructed/dev.jsonl \
    ./cls/en/SST-2/instructed/SST-2_dev.jsonl \
    ./cls/en/Winogrande/new/dev.jsonl \
    ./cls/en/WNLI/processed/WNLI_dev.jsonl \
    ./ent/en/ACE05-EN/instructed/dev.jsonl \
    ./ent/en/ACE05-EN-plus/instructed/dev.jsonl \
    ./ent/en/ACE_2004/instructed/dev.jsonl \
    ./ent/en/AnatEM/instructed/dev.jsonl \
    ./ent/en/bc2gm/instructed/dev.jsonl \
    ./ent/en/bc4chemd/instructed/dev.jsonl \
    ./ent/en/bc5cdr/instructed/dev.jsonl \
    ./ent/en/Broad_Tweet_Corpus/instructed/dev.jsonl \
    ./ent/en/CoNLL2003/instructed/dev.jsonl \
    ./ent/en/CrossNER_AI/instructed/dev.jsonl \
    ./ent/en/CrossNER_literature/instructed/dev.jsonl \
    ./ent/en/CrossNER_music/instructed/dev.jsonl \
    ./ent/en/CrossNER_politics/instructed/dev.jsonl \
    ./ent/en/CrossNER_science/instructed/dev.jsonl \
    ./ent/en/FabNER/instructed/dev.jsonl \
    ./ent/en/FindVehicle/instructed/dev.jsonl \
    ./ent/en/GENIA_NER/instructed/dev.jsonl \
    ./ent/en/HarveyNER/instructed/dev.jsonl \
    ./ent/en/MIT_MOVIE_Review/instructed/dev.jsonl \
    ./ent/en/MIT_Restaurant_Review/instructed/dev.jsonl \
    ./ent/en/MultiNERD/instructed/dev.jsonl \
    ./ent/en/NCBIdiease/instructed/dev.jsonl \
    ./ent/en/ontoNotes5/instructed/dev.jsonl \
    ./ent/en/TweetNER7/instructed/dev.jsonl \
    ./ent/en/WikiANN_en/instructed/dev.jsonl \
    ./ent/en/WNUT-16/dev.jsonl \
    ./event/en/ACE05-EN/instructed/dev.jsonl \
    ./event/en/ACE05-EN-plus/fixed_instructed/dev.jsonl \
    ./event/en/CASIE/instructed/dev.jsonl \
    ./event/en/PHEE/instructed/dev.jsonl \
    ./rel/en/14lap/instructed/dev.jsonl \
    ./rel/en/14res/instructed/dev.jsonl \
    ./rel/en/15res/instructed/dev.jsonl \
    ./rel/en/16res/instructed/dev.jsonl \
    ./rel/en/ACE05-EN/instructed/ACE2005_oneie_RE_labelmap_dev.jsonl \
    ./rel/en/ACE05-EN-plus/instructed/ACE2005_plus_RE_labelmap_dev.jsonl \
    ./rel/en/ADE_corpus/instructed/ADE_corpus_dev.jsonl \
    ./rel/en/CoNLL2004/instructed/CoNLL2004_RE_labelmap_dev.jsonl \
    ./rel/en/GIDS/instructed/GIDS_dev.jsonl \
    ./rel/en/kbp37/instructed/kbp37_dev.jsonl \
    ./rel/en/NYT_multi/instructed/NYT_multi_dev.jsonl \
    ./rel/en/sciERC/instructed/sciERC_dev.jsonl \
    ./rel/en/semeval/instructed/semeval_train.jsonl \
    ./span/en/BiPaR/dev.jsonl \
    ./span/en/ms_marco_v2.1/dev.jsonl \
    ./span/en/newsqa/dev.jsonl \
    ./span/en/squad_v2/dev.jsonl \
    ./span/en/SubjQA/books/dev.jsonl \
    ./span/en/SubjQA/electronics/dev.jsonl \
    ./span/en/SubjQA/grocery/dev.jsonl \
    ./span/en/SubjQA/movies/dev.jsonl \
    ./span/en/SubjQA/restaurants/dev.jsonl \
    ./span/en/SubjQA/tripadvisor/dev.jsonl \
        > $out_dir/dev.jsonl

cat \
    ./cls/en/ag_news/instructed/test.jsonl \
    ./cls/en/ANLI/R1_processed/test.jsonl \
    ./cls/en/ANLI/R2_processed/test.jsonl \
    ./cls/en/ANLI/R3_processed/test.jsonl \
    ./cls/en/ARC/new/test.jsonl \
    ./cls/en/CoLA/formated/test.jsonl \
    ./cls/en/CosmosQA/new/test.jsonl \
    ./cls/en/dbpedia/new/test.jsonl \
    ./cls/en/DREAM/new/test.jsonl \
    ./cls/en/MCTest/new/test_160.jsonl \
    ./cls/en/MCTest/new/test_500.jsonl \
    ./cls/en/MedQA/new/test.jsonl \
    ./cls/en/MRPC/formated/test.jsonl \
    ./cls/en/OpenBookQA/new/test.jsonl \
    ./cls/en/RACE/instructed/test.jsonl \
    ./cls/en/RACE-C/new/test.jsonl \
    ./cls/en/SciQ/instructed/test.jsonl \
    ./cls/en/SNLI/instructed/test.jsonl \
    ./ent/en/ACE05-EN/instructed/test.jsonl \
    ./ent/en/ACE05-EN-plus/instructed/test.jsonl \
    ./ent/en/ACE_2004/instructed/test.jsonl \
    ./ent/en/AnatEM/instructed/test.jsonl \
    ./ent/en/bc2gm/instructed/test.jsonl \
    ./ent/en/bc4chemd/instructed/test.jsonl \
    ./ent/en/bc5cdr/instructed/test.jsonl \
    ./ent/en/Broad_Tweet_Corpus/instructed/test.jsonl \
    ./ent/en/CoNLL2003/instructed/test.jsonl \
    ./ent/en/CrossNER_AI/instructed/test.jsonl \
    ./ent/en/CrossNER_literature/instructed/test.jsonl \
    ./ent/en/CrossNER_music/instructed/test.jsonl \
    ./ent/en/CrossNER_politics/instructed/test.jsonl \
    ./ent/en/CrossNER_science/instructed/test.jsonl \
    ./ent/en/FabNER/instructed/test.jsonl \
    ./ent/en/FindVehicle/instructed/test.jsonl \
    ./ent/en/GENIA_NER/instructed/test.jsonl \
    ./ent/en/HarveyNER/instructed/test.jsonl \
    ./ent/en/MIT_MOVIE_Review/instructed/test.jsonl \
    ./ent/en/MIT_Restaurant_Review/instructed/test.jsonl \
    ./ent/en/MultiNERD/instructed/test.jsonl \
    ./ent/en/NCBIdiease/instructed/test.jsonl \
    ./ent/en/ontoNotes5/instructed/test.jsonl \
    ./ent/en/TweetNER7/instructed/test.jsonl \
    ./ent/en/WikiANN_en/instructed/test.jsonl \
    ./ent/en/WNUT-16/test.jsonl \
    ./event/en/ACE05-EN/instructed/test.jsonl \
    ./event/en/ACE05-EN-plus/fixed_instructed/test.jsonl \
    ./event/en/CASIE/instructed/test.jsonl \
    ./event/en/PHEE/instructed/test.jsonl \
    ./rel/en/14lap/instructed/test.jsonl \
    ./rel/en/14res/instructed/test.jsonl \
    ./rel/en/15res/instructed/test.jsonl \
    ./rel/en/16res/instructed/test.jsonl \
    ./rel/en/ACE05-EN/instructed/ACE2005_oneie_RE_labelmap_test.jsonl \
    ./rel/en/ACE05-EN-plus/instructed/ACE2005_plus_RE_labelmap_test.jsonl \
    ./rel/en/ADE_corpus/instructed/ADE_corpus_test.jsonl \
    ./rel/en/CoNLL2004/instructed/CoNLL2004_RE_labelmap_test.jsonl \
    ./rel/en/GIDS/instructed/GIDS_test.jsonl \
    ./rel/en/kbp37/instructed/kbp37_test.jsonl \
    ./rel/en/New-York-Times-RE/instructed/New_York_Times_test.jsonl \
    ./rel/en/NYT11HRL/instructed/NYT11HRL_test-plus.jsonl \
    ./rel/en/NYT11HRL/instructed/NYT11HRL_test.jsonl \
    ./rel/en/NYT_multi/instructed/NYT_multi_test.jsonl \
    ./rel/en/sciERC/instructed/sciERC_test.jsonl \
    ./rel/en/semeval/instructed/semeval_test.jsonl \
    ./rel/en/Wiki-ZSL/instructed/Wiki_ZSL_0_test.jsonl \
    ./rel/en/Wiki-ZSL/instructed/Wiki_ZSL_1_test.jsonl \
    ./rel/en/Wiki-ZSL/instructed/Wiki_ZSL_2_test.jsonl \
    ./rel/en/Wiki-ZSL/instructed/Wiki_ZSL_3_test.jsonl \
    ./rel/en/Wiki-ZSL/instructed/Wiki_ZSL_4_test.jsonl \
    ./span/en/BiPaR/test.jsonl \
    ./span/en/SubjQA/books/test.jsonl \
    ./span/en/SubjQA/electronics/test.jsonl \
    ./span/en/SubjQA/grocery/test.jsonl \
    ./span/en/SubjQA/movies/test.jsonl \
    ./span/en/SubjQA/restaurants/test.jsonl \
    ./span/en/SubjQA/tripadvisor/test.jsonl \
        > $out_dir/test.jsonl
